[project]
name = "lockbox-number-generator"
version = "0.1.0"
description = "Generates unique 4-digit numbers"
dependencies = ["typer", "rich"]
readme = "README.md"
requires-python = ">=3.12"

[tools]
dependencies = ["ruff"]

[project.optional-dependencies]
dev = ["pytest"]